//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicThemer2 {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    resourceCulture = global::System.Threading.Thread.CurrentThread.CurrentUICulture;
                }
                bool isChinese = resourceCulture != null && resourceCulture.Name.StartsWith("zh");
                string baseName = isChinese ? "BasicThemer2.Strings.zh-CN" : "BasicThemer2.Strings";
                if (object.ReferenceEquals(resourceMan, null) || resourceMan.BaseName != baseName) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(baseName, typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   BasicThemer 2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string ExclsOrInclsLabel {
            get {
                return ResourceManager.GetString("ExclsOrInclsLabel", resourceCulture);
            }
        }
        
        internal static string IncLabels {
            get {
                return ResourceManager.GetString("IncLabels", resourceCulture);
            }
        }
        
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        internal static string RevertingMode {
            get {
                return ResourceManager.GetString("RevertingMode", resourceCulture);
            }
        }
        
        internal static string ExclExtWnds {
            get {
                return ResourceManager.GetString("ExclExtWnds", resourceCulture);
            }
        }
        
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        internal static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        internal static string EnableLogging {
            get {
                return ResourceManager.GetString("EnableLogging", resourceCulture);
            }
        }
        
        internal static string OpenLogFile {
            get {
                return ResourceManager.GetString("OpenLogFile", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string TimerSpeed {
            get {
                return ResourceManager.GetString("TimerSpeed", resourceCulture);
            }
        }
        
        internal static string Ms {
            get {
                return ResourceManager.GetString("Ms", resourceCulture);
            }
        }
        
        internal static string WhitelistMode {
            get {
                return ResourceManager.GetString("WhitelistMode", resourceCulture);
            }
        }
        
        internal static string AutoUpdChk {
            get {
                return ResourceManager.GetString("AutoUpdChk", resourceCulture);
            }
        }
        
        internal static string StartWithWindows {
            get {
                return ResourceManager.GetString("StartWithWindows", resourceCulture);
            }
        }
        
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        internal static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        internal static string Err {
            get {
                return ResourceManager.GetString("Err", resourceCulture);
            }
        }
        
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        internal static string MsgLogFileNotExist {
            get {
                return ResourceManager.GetString("MsgLogFileNotExist", resourceCulture);
            }
        }
        
        internal static string MsgNewVerAvailable {
            get {
                return ResourceManager.GetString("MsgNewVerAvailable", resourceCulture);
            }
        }
        
        internal static string MsgLatestVersion {
            get {
                return ResourceManager.GetString("MsgLatestVersion", resourceCulture);
            }
        }
        
        internal static string MsgUnreleasedVersion {
            get {
                return ResourceManager.GetString("MsgUnreleasedVersion", resourceCulture);
            }
        }
        
        internal static string MsgUpdateFailed {
            get {
                return ResourceManager.GetString("MsgUpdateFailed", resourceCulture);
            }
        }
        
        internal static string DbgInfo {
            get {
                return ResourceManager.GetString("DbgInfo", resourceCulture);
            }
        }
        
        internal static string DbgInfoTitle {
            get {
                return ResourceManager.GetString("DbgInfoTitle", resourceCulture);
            }
        }
        
        internal static string CmdHelp {
            get {
                return ResourceManager.GetString("CmdHelp", resourceCulture);
            }
        }
        
        internal static string CmdHelpTitle {
            get {
                return ResourceManager.GetString("CmdHelpTitle", resourceCulture);
            }
        }
        
        internal static string CmdVersion {
            get {
                return ResourceManager.GetString("CmdVersion", resourceCulture);
            }
        }
        
        internal static string AdminPrompt {
            get {
                return ResourceManager.GetString("AdminPrompt", resourceCulture);
            }
        }
        
        internal static string AdminAborted {
            get {
                return ResourceManager.GetString("AdminAborted", resourceCulture);
            }
        }
        
        internal static string VersionLine {
            get {
                return ResourceManager.GetString("VersionLine", resourceCulture);
            }
        }
        
        internal static string Watermark {
            get {
                return ResourceManager.GetString("Watermark", resourceCulture);
            }
        }
        
        internal static string DebugBtn {
            get {
                return ResourceManager.GetString("DebugBtn", resourceCulture);
            }
        }
        
        internal static string ForkLink {
            get {
                return ResourceManager.GetString("ForkLink", resourceCulture);
            }
        }
        
        internal static string BrandLine {
            get {
                return ResourceManager.GetString("BrandLine", resourceCulture);
            }
        }
        
        internal static string MsgAlreadyRunning {
            get {
                return ResourceManager.GetString("MsgAlreadyRunning", resourceCulture);
            }
        }
    }
}
